name: Dot net core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
  
      - name: Restore dependencies
        run: dotnet restore WebApplication1/WebApplication1/WebApplication1.csproj
  
      - name: Build
        run: dotnet build --no-restore dotnet restore
  
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
